# Generated by Django 5.2.14 on 2026-06-19 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provinsi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_prov', models.CharField(max_length=10, unique=True)),
                ('nama', models.CharField(max_length=100, unique=True)),
                ('geometry', models.JSONField()),
            ],
            options={
                'db_table': 'provinsi',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='DataPerceraian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.PositiveSmallIntegerField(default=2023)),
                ('jumlah_perceraian', models.IntegerField()),
                ('faktor_perselisihan', models.IntegerField()),
                ('faktor_ekonomi', models.IntegerField()),
                ('provinsi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data_perceraian', to='webPerceraian_indonesia.provinsi')),
            ],
            options={
                'db_table': 'data_perceraian',
            },
        ),
    ]
