# Generated by Django 6.0.5 on 2026-06-03 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beranda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='province',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='province',
            name='alt_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='province',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='province',
            table='provinces',
        ),
    ]
