# Generated by Django 6.0.5 on 2026-06-03 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beranda', '0004_regency_delete_kabupaten'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('alt_name', models.CharField(blank=True, default='', max_length=255)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('regency', models.ForeignKey(db_column='regency_id', on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='beranda.regency')),
            ],
            options={
                'db_table': 'districts',
                'managed': True,
            },
        ),
    ]
