# Generated by Django 5.2.14 on 2026-06-10 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beranda', '0005_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='NamaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Datprof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.IntegerField()),
                ('jumlah', models.FloatField()),
                ('province', models.ForeignKey(db_column='province_id', on_delete=django.db.models.deletion.CASCADE, related_name='datprof_provinces', to='beranda.province')),
                ('nama', models.ForeignKey(db_column='nama_id', on_delete=django.db.models.deletion.CASCADE, related_name='datprof_nama', to='beranda.namadata')),
            ],
            options={
                'db_table': 'data_provinces',
                'managed': True,
            },
        ),
    ]
